/* InstaLume — local-only social simulator. Created By Shiv Yogi. Not affiliated with Instagram/Meta. */
const E=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const H=s=>{let x=5381;for(const c of String(s))x=((x*33)^c.charCodeAt(0))>>>0;return x};
const T={hi:{home:'होम',reels:'रील्स',create:'बनाएँ',search:'खोजें',profile:'प्रोफ़ाइल'},en:{home:'Home',reels:'Reels',create:'Create',search:'Search',profile:'Profile'}};
const art=(s,e='✨')=>{const h=H(s)%360;return 'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 400"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="hsl(${h},80%,60%)"/><stop offset="1" stop-color="hsl(${(h+70)%360},85%,55%)"/></linearGradient></defs><rect width="400" height="400" fill="url(#g)"/><text x="200" y="250" font-size="150" text-anchor="middle">${e}</text></svg>`)};
const IDB=()=>new Promise(r=>{const q=indexedDB.open('instalume',1);q.onupgradeneeded=()=>q.result.createObjectStore('k');q.onsuccess=()=>r(q.result)});
const load=async()=>{const d=await IDB();return new Promise(r=>{const g=d.transaction('k').objectStore('k').get('db');g.onsuccess=()=>r(g.result);g.onerror=()=>r()})};
let tm,D,S={mode:'choose',tab:'home',page:null,pu:null,cu:null,rep:null,edit:null,tmp:null};
const saveNow=async()=>{const d=await IDB();d.transaction('k','readwrite').objectStore('k').put(D,'db')};
const save=()=>{clearTimeout(tm);tm=setTimeout(saveNow,150)};
const SP=[['luna.art','Luna Rao','Digital artist 🎨 | colours & chai','🎨'],['rohit.rides','Rohit Verma','Bike trips • Rajasthan 🏍','🏍'],['priya.cooks','Priya Sharma','Home chef 🍛 | Hinglish recipes','🍛'],['star.striker','Star Striker','Football ⚽ (fictional demo star)','⚽'],['private.pari','Pari','Private account 🔒','🔒']];
const mk=u=>({username:u,name:u,bio:'Naya InstaLume account ✨',website:'',avatar:'',followers:0,following:0,private:false,hl:[],nPosts:null});
function seed(){const d={accts:{},cur:null,P:{},posts:[],stories:[],fol:[],saved:[],dm:{},nt:[],rep:[],set:{theme:'auto',lang:'hi',notif:true,sim:true},id:1};
SP.forEach(([u,n,b,e],i)=>{d.P[u]={...mk(u),name:n,bio:b,followers:1000*(i+3)+137,following:100+i*20,private:u=='private.pari',hl:['🌅','🎉','✈️'].map((x,k)=>({t:['Morning','Fun','Trip'][k],src:art(u+x,x)}))};
if(!d.P[u].private){for(let k=0;k<3;k++)d.posts.push({id:d.id++,u,type:'img',src:art(u+k,e),cap:`${b.split(' ')[0]} vibes #${k+1} ${e}`,likes:[],cm:[{u:'luna.art',t:'Mast! 🔥'}],ts:Date.now()-(i*3+k+1)*36e5});d.posts.push({id:d.id++,u,type:'demo',r:1,src:art(u+'reel','🎬'),cap:`${e} Demo reel by ${n} #fun`,likes:[],cm:[],ts:Date.now()-i*9e5});}
d.stories.push({id:d.id++,u,base:{t:'img',src:art(u+'st',e)},filter:0,ov:'',audio:'',ts:Date.now()});});
d.dm['priya.cooks']=[{id:1,me:0,t:'कल आ रहे हो? 😁',seen:1},{id:2,me:1,t:'हाँ भाई 😂',seen:1}];d.dm['rohit.rides']=[{id:3,me:0,t:'Trip ka plan ready hai bhai 🏍',seen:1}];
d.nt=[{id:1,u:'luna.art',txt:'ne aapka swagat kiya 👋',ts:Date.now()-6e5},{id:2,u:'rohit.rides',txt:'ne aapko mention kiya',ts:Date.now()-9e5}];return d}
const L=()=>T[D.set.lang],me=()=>D.P[D.cur],mine=u=>u==D.cur;
const ago=t=>{const s=(Date.now()-t)/1e3;return s<60?'abhi':s<3600?(s/60|0)+' min pehle':s<86400?(s/3600|0)+' ghante pehle':(s/86400|0)+' din pehle'};
const toast=m=>{const t=E('toast');t.textContent=m;t.className='on';clearTimeout(toast.t);toast.t=setTimeout(()=>t.className='',2200)};
const av=(p,s=40)=>`<img class="av" style="--s:${s}px" alt="" src="${p&&p.avatar||art((p&&p.username)||'x','🙂')}">`;
const M=(h,c='')=>{E('modal').innerHTML=`<div class="mb" data-a="mx"><div class="mc ${c}">${h}</div></div>`};const closeM=()=>{E('modal').innerHTML='';clearTimeout(S.stt)};
function theme(){const t=D.set.theme;document.documentElement.dataset.theme=t=='auto'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):t}
function pick(acc,cb){const f=E('file');f.accept=acc;f.value='';f.onchange=()=>{const x=f.files[0];if(!x)return;const r=new FileReader();r.onload=()=>cb(r.result,x.type.startsWith('video')?'vid':'img',x);r.readAsDataURL(x)};f.click()}
const addNt=(u,txt)=>{if(!D.set.notif)return;D.nt.unshift({id:D.id++,u,txt,ts:Date.now()});save();R()};
const rnd=a=>a[Math.random()*a.length|0],pubs=()=>SP.filter(x=>x[0]!='private.pari').map(x=>x[0]);
function simulate(p){if(!D.set.sim)return;setTimeout(()=>{const u=rnd(pubs());if(!D.posts.includes(p)||p.likes.includes(u))return;p.likes.push(u);addNt(u,'ne aapki post like ki ❤️');if(Math.random()>.4)setTimeout(()=>{const t=rnd(['Zabardast! 🔥','Bahut badhiya 😍','Mast hai bhai 😂']);p.cm.push({u,t});addNt(u,'ne comment kiya: '+t)},1500);if(Math.random()>.6)setTimeout(()=>addNt(rnd(pubs()),'ne aapko post me mention kiya @'+D.cur),3000)},2500)}
/* ---------- views ---------- */
const authV=()=>{const m=S.mode;return `<div class="auth"><h1 class="logo big">InstaLume</h1>`+(m=='choose'?`<div class="glass pad"><button class="btn" data-a="mode" data-v="login">Log in</button><button class="btn gl" data-a="mode" data-v="create">Create account</button></div>`:`<div class="glass pad"><input id="au" placeholder="Username" autocapitalize="off" autocomplete="off"><input id="ap" type="password" placeholder="Password">${m=='create'?'<input id="ap2" type="password" placeholder="Confirm Password">':''}<button class="btn" data-a="${m}Go">${m=='login'?'Log in':'Create account'}</button><a data-a="mode" data-v="choose">← Back</a></div>`)+`<p class="note">Independent fun simulation. Yeh real Instagram login nahi hai. Password sirf is browser ke local demo ke liye hai — kahin bhejà ya Instagram ko nahi jaata.</p><p class="by">Created By Shiv Yogi</p></div>`};
const media=(p,r)=>p.type=='vid'?`<video src="${p.src}" playsinline loop ${r?'muted autoplay':'controls'}></video>`:p.type=='demo'?`<img class="kb" src="${p.src}">`:`<img src="${p.src}">`;
const card=p=>{const u=D.P[p.u]||{username:p.u},lk=p.likes.includes(D.cur),sv=D.saved.includes(p.id);return `<article class="card glass"><header><div class="who" data-a="user" data-v="${esc(p.u)}">${av(u,36)}<b>${esc(p.u)}</b></div><button class="ib" data-a="menu" data-v="${p.id}">⋯</button></header><div class="media">${media(p)}</div><div class="acts"><button class="ib ${lk?'on':''}" data-a="like" data-v="${p.id}">${lk?'❤️':'🤍'}</button><button class="ib" data-a="cm" data-v="${p.id}">💬</button><button class="ib" data-a="share" data-v="${p.id}">📤</button><button class="ib r" data-a="save" data-v="${p.id}">${sv?'🔖':'📑'}</button></div><span class="lk"><b>${p.likes.length}</b> likes</span><p class="cap"><b>${esc(p.u)}</b> ${esc(p.cap)}</p><a class="vc" data-a="cm" data-v="${p.id}">${p.cm.length} comments dekhein</a><small>${ago(p.ts)}</small></article>`};
const storyBar=()=>{const us=[...new Set(D.stories.map(s=>s.u))].filter(u=>u!=D.cur);const my=D.stories.some(s=>s.u==D.cur);return `<div class="st" data-a="ed_open"><div class="ring">${av(me(),56)}</div>Your story ➕</div>`+(my?`<div class="st" data-a="story" data-v="${esc(D.cur)}"><div class="ring">${av(me(),56)}</div>You</div>`:'')+us.map(u=>`<div class="st" data-a="story" data-v="${esc(u)}"><div class="ring">${av(D.P[u],56)}</div>${esc(u)}</div>`).join('')};
const homeV=()=>`<div class="stories">${storyBar()}</div>`+(D.posts.slice().sort((a,b)=>b.ts-a.ts).map(card).join('')||'<p class="empty">Abhi koi post nahi</p>');
const reelsV=()=>{const rs=D.posts.filter(p=>p.r).sort((a,b)=>b.ts-a.ts);return rs.length?`<div class="reels">${rs.map(p=>{const lk=p.likes.includes(D.cur);return `<section class="reel" data-a="rtap" data-v="${p.id}"><div class="rm">${media(p,1)}</div><div class="side"><button class="ib" data-a="like" data-v="${p.id}">${lk?'❤️':'🤍'}</button><small>${p.likes.length}</small><button class="ib" data-a="cm" data-v="${p.id}">💬</button><small>${p.cm.length}</small><button class="ib" data-a="share" data-v="${p.id}">📤</button><button class="ib" data-a="save" data-v="${p.id}">${D.saved.includes(p.id)?'🔖':'📑'}</button><button class="ib" data-a="mute">🔊</button><button class="ib" data-a="menu" data-v="${p.id}">⋯</button></div><div class="rd"><b>@${esc(p.u)}</b><p>${esc(p.cap)}</p></div></section>`}).join('')}</div>`:'<p class="empty">Koi reel nahi. Create → Reel se banayein.</p>'};
const createV=()=>`<h3 class="sec">Create</h3><div class="cr"><button class="glass" data-a="mkpost">📷 Post</button><button class="glass" data-a="ed_open">⭕ Story</button><button class="glass" data-a="mkreel">🎬 Reel</button></div>`;
const resV=q=>{q=q.trim().toLowerCase().replace(/^@/,'');const r=Object.values(D.P).filter(p=>!q||p.username.includes(q)||p.name.toLowerCase().includes(q));let h=r.map(p=>`<div class="li glass" data-a="user" data-v="${esc(p.username)}">${av(p,48)}<div class="g"><b>${esc(p.username)}</b>${p.private?' 🔒':''}<p>${esc(p.name)} • ${p.followers} followers</p></div></div>`).join('');if(/^[a-z0-9._]{3,30}$/.test(q)&&!D.P[q])h+=`<div class="li glass" data-a="user" data-v="${q}">${av({username:q},48)}<div class="g"><b>@${q}</b><p>Local simulated profile kholein (koi external fetch nahi)</p></div></div>`;return h||'<p class="empty">Kuch nahi mila</p>'};
const searchV=()=>`<input id="q" placeholder="🔍 Search username / profile" value="${esc(S.q||'')}"><div id="res">${resV(S.q||'')}</div>`;
function profV(u){let p=D.P[u];if(!p)p=D.P[u]=mk(u);const mi=mine(u),ps=D.posts.filter(x=>x.u==u),pv=p.private&&!mi,f=D.fol.includes(u);
return `<div class="glass" style="margin-top:8px"><div class="ph">${av(p,80)}<div class="stat"><div><b>${p.nPosts??ps.length}</b>Posts</div><div><b>${p.followers}</b>Followers</div><div><b>${p.following}</b>Following</div></div></div><div class="bio"><b>${esc(p.name)}</b> ${p.private?'🔒':''}\n${esc(p.bio)}${p.website?`\n<a href="${esc(/^https?:/.test(p.website)?p.website:'https://'+p.website)}" target="_blank" rel="noopener">${esc(p.website)}</a>`:''}\n<small>Local simulated profile — real Instagram par koi asar nahi</small></div>
<div class="row">${mi?`<button class="btn gl" data-a="editp" data-v="${esc(u)}">Edit profile</button><button class="btn gl" data-a="set">⚙️ Settings</button>`:`<button class="btn ${f?'gl':''}" data-a="follow" data-v="${esc(u)}">${f?'Following':'Follow'}</button><button class="btn gl" data-a="chat" data-v="${esc(u)}">Message</button><button class="btn gl" data-a="editp" data-v="${esc(u)}">Edit (local)</button>`}</div>
<div class="hls">${pv?'<small>Highlights: Loading…</small>':p.hl.map((h,i)=>`<div class="st" data-a="hl" data-v="${esc(u)}|${i}"><div class="ring">${av({avatar:h.src},56)}</div>${esc(h.t)}</div>`).join('')||'<small>Koi highlight nahi</small>'}</div></div>
<div style="margin-top:12px">${pv?'<p class="empty">Posts: Loading…</p>':ps.length?`<div class="grid">${ps.map(x=>`<div data-a="open" data-v="${x.id}">${x.type=='vid'?`<video src="${x.src}" muted></video>`:`<img src="${x.src}">`}</div>`).join('')}</div>`:'<p class="empty">Abhi koi post nahi</p>'}</div>`}
const dmV=()=>`<h3 class="sec">Messages</h3>`+(Object.keys(D.dm).map(u=>{const l=D.dm[u].at(-1);return `<div class="li glass" data-a="chat" data-v="${esc(u)}">${av(D.P[u]||{username:u},48)}<div class="g"><b>${esc(u)}</b><p>${l?(l.me?'You: ':'')+esc(l.t):''}</p></div></div>`}).join('')||'<p class="empty">Koi conversation nahi. Profile se Message dabayein.</p>');
const EM=['😁','😂','😍','🔥','👍','❤️','🙏','😎','🎉','🥳','😢','🤝'];
const chatV=()=>{const u=S.cu,ms=D.dm[u]||[],rp=S.rep&&ms.find(m=>m.id==S.rep);return `<h3 class="sec" data-a="user" data-v="${esc(u)}">${av(D.P[u]||{username:u},32)} @${esc(u)}</h3><div class="msgs">${ms.map(m=>{const q=m.rep&&ms.find(x=>x.id==m.rep);return `<div class="msg ${m.me?'me':''}">${q?`<div class="q">${esc(q.t)}</div>`:''}${esc(m.t)}${m.ed?' <small>(edited)</small>':''}<small>${m.me?(m.seen?'Seen ✓✓':'Sent ✓'):''}</small><span class="ab"><button data-a="mrep" data-v="${m.id}">↩ Reply</button>${m.me?`<button data-a="medit" data-v="${m.id}">✎ Edit</button>`:''}<button data-a="mdel" data-v="${m.id}">🗑 Delete</button></span></div>`}).join('')}</div><div class="mbar glass">${rp?`<small>Reply: ${esc(rp.t)} <a data-a="mcancel">✕</a></small>`:''}${S.edit?`<small>Editing <a data-a="mcancel">✕</a></small>`:''}<div class="emo">${EM.map(e=>`<button data-a="emo" data-v="${e}">${e}</button>`).join('')}</div><div class="cbar"><input id="msg" placeholder="Message…" value="${S.edit?esc(ms.find(m=>m.id==S.edit)?.t||''):''}"><button class="btn" data-a="send">Send</button></div></div>`};
const ntV=()=>`<h3 class="sec">Notifications</h3>`+(D.nt.map(n=>`<div class="li glass" data-a="user" data-v="${esc(n.u)}">${av(D.P[n.u]||{username:n.u},44)}<div class="g"><b>${esc(n.u)}</b> ${esc(n.txt)}<p>${ago(n.ts)}</p></div></div>`).join('')||'<p class="empty">Koi notification nahi</p>');
const setV=()=>{const s=D.set;return `<h3 class="sec">Settings</h3>
<details class="glass"><summary>Account</summary><div><p>@${esc(D.cur)}</p><button class="btn gl" data-a="pw">Password badlein</button><button class="btn gl" data-a="logout">Log out</button></div></details>
<details class="glass"><summary>Profile</summary><div><button class="btn gl" data-a="editp" data-v="${esc(D.cur)}">Edit profile</button></div></details>
<details class="glass"><summary>Privacy</summary><div><label class="sw">Private account (local)<input type="checkbox" data-c="priv" ${me().private?'checked':''} style="width:auto"></label></div></details>
<details class="glass"><summary>Notifications</summary><div><label class="sw">Simulated notifications<input type="checkbox" data-c="notif" ${s.notif?'checked':''} style="width:auto"></label><label class="sw">Auto likes/comments on my posts<input type="checkbox" data-c="sim" ${s.sim?'checked':''} style="width:auto"></label></div></details>
<details class="glass"><summary>Appearance</summary><div><select data-c="theme"><option value="auto" ${s.theme=='auto'?'selected':''}>Auto</option><option value="light" ${s.theme=='light'?'selected':''}>☀️ Light</option><option value="dark" ${s.theme=='dark'?'selected':''}>🌙 Dark</option></select></div></details>
<details class="glass"><summary>Language</summary><div><select data-c="lang"><option value="hi" ${s.lang=='hi'?'selected':''}>हिन्दी</option><option value="en" ${s.lang=='en'?'selected':''}>English</option></select></div></details>
<details class="glass"><summary>Storage</summary><div><p id="stg">Calculating…</p><button class="btn gl" data-a="export">Local data export (JSON)</button></div></details>
<details class="glass" open><summary>About</summary><div><b>About This Experience</b><p>This is an independent fan-made social media experience created for fun and educational purposes.</p><p>Content shown from external platforms remains the property of its respective creators and platforms.</p><p>This project does not hack, modify, control or access private social-media accounts.</p><p>Instagram is a trademark of Meta Platforms, Inc. This project is not affiliated with or endorsed by Instagram or Meta.</p><a class="btn gl" href="https://instagram.com" target="_blank" rel="noopener" style="text-align:center;text-decoration:none">Official Instagram ↗</a><small>Created By Shiv Yogi</small></div></details>
<details class="glass"><summary>Reset Local Data</summary><div><button class="btn red" data-a="reset">Reset Simulation</button></div></details>`};
function R(top){const y=scrollY,a=E('app');theme();if(!D.cur){a.innerHTML=authV();return}
const t=S.tab,pg=S.page;let b;if(pg=='dm')b=dmV();else if(pg=='chat')b=chatV();else if(pg=='nt')b=ntV();else if(pg=='set')b=setV();else if(pg=='user')b=profV(S.pu);else b={home:homeV,reels:reelsV,create:createV,search:searchV,profile:()=>profV(D.cur)}[t]();
const un=D.nt.filter(n=>!n.r).length;
a.innerHTML=`<div class="top glass" style="margin-top:8px;padding:8px 14px"><div style="display:flex;gap:8px;align-items:center">${pg?'<button class="ib" data-a="back">←</button>':''}<span class="logo">InstaLume</span></div><div class="r"><button class="ib" data-a="dm">✉️</button><button class="ib" data-a="nt">🔔${un?`<span class="bd">${un}</span>`:''}</button></div></div>${b}<p class="by" style="margin-top:20px">Created By Shiv Yogi</p><nav class="glass">${[['home','🏠'],['reels','🎬'],['create','➕'],['search','🔍'],['profile','👤']].map(([k,i])=>`<button class="${!pg&&t==k?'on':''}" data-a="tab" data-v="${k}">${i}<span>${L()[k]}</span></button>`).join('')}</nav>`;
scrollTo(0,top?0:y);if(!pg&&t=='reels')reelSetup();if(pg=='set')navigator.storage?.estimate?.().then(e=>{const s=E('stg');if(s)s.textContent=`Use: ${(e.usage/1048576).toFixed(2)} MB / ${(e.quota/1048576|0)} MB`});if(pg=='chat')scrollTo(0,1e6)}
function reelSetup(){const io=new IntersectionObserver(es=>es.forEach(x=>{const v=x.target.querySelector('video');if(v)x.isIntersecting?v.play().catch(()=>{}):v.pause()}),{threshold:.7});document.querySelectorAll('.reel').forEach(r=>io.observe(r))}
const go=(o)=>{Object.assign(S,o);closeM();R(1)};
/* ---------- helpers ---------- */
const P=id=>D.posts.find(p=>p.id==id);
function rename(o,n){if(o==n)return;D.P[n]=D.P[o];D.P[n].username=n;delete D.P[o];D.posts.forEach(x=>{if(x.u==o)x.u=n;x.likes=x.likes.map(l=>l==o?n:l);x.cm.forEach(c=>{if(c.u==o)c.u=n})});D.stories.forEach(x=>{if(x.u==o)x.u=n});D.fol=D.fol.map(f=>f==o?n:f);if(D.dm[o]){D.dm[n]=D.dm[o];delete D.dm[o]}D.nt.forEach(x=>{if(x.u==o)x.u=n});if(D.accts[o]){D.accts[n]=D.accts[o];delete D.accts[o]}if(D.cur==o)D.cur=n;if(S.pu==o)S.pu=n;if(S.cu==o)S.cu=n}
function cmModal(id){const p=P(id);M(`<h3>Comments</h3>${p.cm.map((c,i)=>`<div class="cmt"><b>${esc(c.u)}</b> ${esc(c.t)} ${c.u==D.cur?`<a data-a="cdel" data-v="${id}|${i}">🗑</a>`:''}</div>`).join('')||'<p class="empty">Pehla comment karein</p>'}<div class="cbar"><input id="cmt" placeholder="Comment likhein…"><button class="btn" data-a="cpost" data-v="${id}">Post</button></div>`)}
function menuModal(id){const p=P(id),o=mine(p.u);M(`<h3>Options</h3><button class="mi" data-a="share" data-v="${id}">📤 Share</button><button class="mi" data-a="save" data-v="${id}">${D.saved.includes(id)?'🔖 Unsave':'📑 Save'}</button><button class="mi" data-a="desc" data-v="${id}">📝 Description</button><a class="mi" href="${p.src}" download="instalume-${id}.${p.type=='vid'?'mp4':p.src.startsWith('data:image/svg')?'svg':'png'}" style="text-decoration:none;color:inherit">⬇️ Download (local content)</a>${o?`<button class="mi" data-a="pedit" data-v="${id}">✎ Caption edit</button><button class="mi red" data-a="pdel" data-v="${id}">🗑 Delete</button>`:''}<button class="mi" data-a="report" data-v="${id}">🚩 Report</button><button class="mi" data-a="more" data-v="${id}">➕ More (link copy)</button>`)}
function editModal(u){const p=D.P[u];S.tmp={hl:p.hl.map(h=>({...h})),avatar:p.avatar,u};M(`<h3>Edit profile (local)</h3><div style="text-align:center">${av({avatar:p.avatar,username:u},80)}</div><button class="mi" data-a="eav">🖼 Profile photo badlein</button><input id="e_u" value="${esc(u)}" placeholder="Username"><input id="e_n" value="${esc(p.name)}" placeholder="Name"><textarea id="e_b" placeholder="Bio">${esc(p.bio)}</textarea><input id="e_w" value="${esc(p.website)}" placeholder="Website"><input id="e_f" type="number" min="0" value="${p.followers}" placeholder="Followers"><input id="e_g" type="number" min="0" value="${p.following}" placeholder="Following"><input id="e_p" type="number" min="0" value="${p.nPosts??D.posts.filter(x=>x.u==u).length}" placeholder="Posts"><b>Highlights</b><div id="e_h">${hlList()}</div><button class="mi" data-a="hladd">➕ Highlight add</button><button class="btn" data-a="esave">Save</button>`)}
const hlList=()=>S.tmp.hl.map((h,i)=>`<div class="cmt">${esc(h.t)} <a data-a="hldel" data-v="${i}">🗑</a></div>`).join('')||'<small>Koi nahi</small>';
/* ---------- story editor ---------- */
const COL=['#ffffff','#ff5d8f','#ffd93d','#4ade80','#38bdf8','#a24cf0','#000000'],FNT=['system-ui','cursive','serif','monospace','Impact'],FIL=['Normal','grayscale(1)','sepia(.8)','saturate(1.8) contrast(1.1)','hue-rotate(90deg)','brightness(1.2) blur(.5px)','invert(.85)'];
let ed;const IM={};const img=s=>IM[s]||(IM[s]=Object.assign(new Image,{src:s,onload:()=>ed&&drawEd()}));
const fl=i=>i?FIL[i]:'none';
function bgSet(){const b=E('bg');b.innerHTML=ed.base.t=='vid'?`<video src="${ed.base.src}" autoplay muted loop playsinline></video>`:`<img src="${ed.base.src}">`;b.style.filter=fl(ed.filter)}
function drawEd(){const cv=E('cv');if(!cv)return;const c=cv.getContext('2d');c.clearRect(0,0,360,640);ed.strokes.forEach(s=>{c.strokeStyle=s.c;c.lineWidth=s.w;c.lineCap=c.lineJoin='round';c.beginPath();s.p.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));c.stroke()});
ed.objs.forEach((o,i)=>{c.save();c.translate(o.x,o.y);c.rotate(o.r*Math.PI/180);if(o.k=='t'){c.font=`700 ${o.s}px ${o.f}`;c.textAlign='center';c.textBaseline='middle';c.fillStyle=o.c;c.shadowColor='rgba(0,0,0,.5)';c.shadowBlur=6;c.fillText(o.t,0,0);if(i==ed.sel){const w=c.measureText(o.t).width;c.shadowBlur=0;c.strokeStyle='#fff';c.setLineDash([6,4]);c.strokeRect(-w/2-8,-o.s/2-6,w+16,o.s+12)}}else{const im=img(o.src);if(im.complete&&im.width){const h=o.s*im.height/im.width;c.drawImage(im,-o.s/2,-h/2,o.s,h);if(i==ed.sel){c.strokeStyle='#fff';c.setLineDash([6,4]);c.strokeRect(-o.s/2-4,-h/2-4,o.s+8,h+8)}}}c.restore()})}
const snap=()=>{ed.un.push(JSON.stringify({o:ed.objs,s:ed.strokes,f:ed.filter}));ed.re=[]};
const rest=j=>{const x=JSON.parse(j);ed.objs=x.o;ed.strokes=x.s;ed.filter=x.f;ed.sel=-1;bgSet();drawEd()};
function edBind(){const cv=E('cv');let dr=null;const pt=e=>{const r=cv.getBoundingClientRect();return[(e.clientX-r.left)*360/r.width,(e.clientY-r.top)*640/r.height]};
cv.onpointerdown=e=>{cv.setPointerCapture(e.pointerId);const[x,y]=pt(e);snap();if(ed.draw){ed.strokes.push({c:COL[ed.ci%COL.length],w:5,p:[[x,y]]});dr='d';return}let h=-1;ed.objs.forEach((o,i)=>{if(Math.hypot(o.x-x,o.y-y)<(o.k=='t'?Math.max(o.t.length*o.s*.3,30):o.s/2))h=i});ed.sel=h;dr=h>=0?{dx:ed.objs[h].x-x,dy:ed.objs[h].y-y}:null;if(h<0)ed.un.pop();drawEd()};
cv.onpointermove=e=>{if(!dr)return;const[x,y]=pt(e);if(dr=='d')ed.strokes.at(-1).p.push([x,y]);else{const o=ed.objs[ed.sel];o.x=x+dr.dx;o.y=y+dr.dy}drawEd()};cv.onpointerup=()=>dr=null}
function edOpen(){closeM();ed={base:{t:'img',src:art('new'+Date.now(),'🌈')},filter:0,objs:[],strokes:[],audio:'',sel:-1,draw:false,un:[],re:[],ci:0,fi:0};const d=document.createElement('div');d.className='ed';d.id='ed';
d.innerHTML=`<div class="stage"><div id="bg"></div><canvas id="cv" width="360" height="640"></canvas></div><div class="tools glass">${[['gal','🖼'],['mus','🎵'],['txt','🔤'],['stk','🏷'],['drw','✏️'],['flt','🎨'],['un','↩'],['re','↪'],['del','🗑'],['big','A+'],['sml','A−'],['rot','⟳'],['col','◐'],['fnt','Aa']].map(([a,l])=>`<button class="ib" data-a="ed_${a}">${l}</button>`).join('')}</div><div class="edtop"><button class="btn gl sm" data-a="ed_x">✕</button><button class="btn sm" data-a="ed_ok">Share to Story</button></div><audio id="eda" loop></audio>`;document.body.appendChild(d);bgSet();edBind();drawEd()}
const edClose=()=>{E('ed')?.remove();ed=null};
function viewStory(u,i=0){clearTimeout(S.stt);const l=D.stories.filter(s=>s.u==u),s=l[i];if(!s)return closeM();E('modal').innerHTML=`<div class="sv" data-a="svn" data-v="${esc(u)}|${i}"><div class="stage"><div id="bg" style="filter:${fl(s.filter)}">${s.base.t=='vid'?`<video src="${s.base.src}" autoplay loop playsinline></video>`:`<img src="${s.base.src}">`}</div>${s.ov?`<img src="${s.ov}" style="position:absolute;inset:0;width:100%;height:100%">`:''}<div class="pb"><i></i></div><div class="nm">@${esc(u)} • ${ago(s.ts||Date.now())}</div>${s.audio?`<audio src="${s.audio}" autoplay loop></audio>`:''}</div></div>`;S.stt=setTimeout(()=>viewStory(u,i+1),5000)}
/* ---------- actions ---------- */
const A={
mx:(v,t,e)=>{if(e.target==t)closeM()},mode:v=>{S.mode=v;R()},
loginGo(){const u=E('au').value.trim().toLowerCase().replace(/^@/,''),p=E('ap').value;if(!/^[a-z0-9._]{3,30}$/.test(u))return toast('Username 3-30 chars (a-z 0-9 . _)');if(p.length<4)return toast('Password kam se kam 4 chars');if(D.accts[u]){if(D.accts[u]!=H(p))return toast('Galat password');}else{D.accts[u]=H(p);D.P[u]=D.P[u]||mk(u);toast('Local simulated account ban gaya')}D.cur=u;S.tab='home';save();R(1)},
createGo(){const u=E('au').value.trim().toLowerCase().replace(/^@/,''),p=E('ap').value;if(!/^[a-z0-9._]{3,30}$/.test(u))return toast('Username 3-30 chars (a-z 0-9 . _)');if(D.accts[u])return toast('Username le liya gaya hai');if(p.length<4)return toast('Password kam se kam 4 chars');if(p!=E('ap2').value)return toast('Passwords match nahi karte');D.accts[u]=H(p);D.P[u]=D.P[u]||mk(u);D.cur=u;S.tab='home';save();R(1)},
tab:v=>go({tab:v,page:null}),back(){go({page:S.page=='chat'?'dm':null,tab:S.tab})},dm:()=>go({page:'dm'}),nt(){D.nt.forEach(n=>n.r=1);save();go({page:'nt'})},set:()=>go({page:'set'}),
user:v=>go({page:'user',pu:v,tab:S.tab}),
like(v){const p=P(+v),i=p.likes.indexOf(D.cur);i<0?p.likes.push(D.cur):p.likes.splice(i,1);save();R()},
save(v){const i=D.saved.indexOf(+v);i<0?D.saved.push(+v):D.saved.splice(i,1);save();toast(i<0?'Saved 🔖':'Unsaved');closeM();R()},
cm:v=>cmModal(+v),cpost(v){const t=E('cmt').value.trim();if(!t)return;P(+v).cm.push({u:D.cur,t});save();cmModal(+v);R()},cdel(v){const[i,j]=v.split('|');P(+i).cm.splice(+j,1);save();cmModal(+i);R()},
async share(v){const p=P(+v),d={title:'InstaLume',text:`@${p.u}: ${p.cap}`,url:location.href};try{if(navigator.share)await navigator.share(d);else{await navigator.clipboard.writeText(d.text+' '+d.url);toast('Link copy ho gaya')}}catch(e){}},
menu:v=>menuModal(+v),desc(v){const p=P(+v);M(`<h3>Description</h3><p>${esc(p.cap)}</p><small>@${esc(p.u)} • ${ago(p.ts)}</small>`)},
report(v){M(`<h3>Report</h3>${['Spam','Nudity','Hate / harassment','Misinformation','Other'].map(r=>`<button class="mi" data-a="rep" data-v="${v}|${r}">${r}</button>`).join('')}`)},rep(v){const[i,r]=v.split('|');D.rep.push({id:+i,r});save();closeM();toast('Report local save hui (kahin bheji nahi gayi)')},
async more(v){try{await navigator.clipboard.writeText(location.href+'#post'+v);toast('Link copy hua')}catch(e){toast('Copy nahi ho paya')}closeM()},
pedit(v){const p=P(+v);M(`<h3>Caption edit</h3><textarea id="cap">${esc(p.cap)}</textarea><button class="btn" data-a="pcap" data-v="${v}">Save</button>`)},pcap(v){P(+v).cap=E('cap').value;save();closeM();R()},
pdel(v){if(!confirm('Post delete karein?'))return;D.posts=D.posts.filter(p=>p.id!=v);D.saved=D.saved.filter(x=>x!=v);save();closeM();R()},
open(v){const p=P(+v);M(card(p),'')},
follow(v){const i=D.fol.indexOf(v),p=D.P[v];if(i<0){D.fol.push(v);p.followers++;me().following++;toast('Followed (local)');setTimeout(()=>addNt(v,'ne aapko follow kiya (followed you)'),1800);setTimeout(()=>{if(D.fol.includes(v)){me().followers++;save();R()}},1900)}else{D.fol.splice(i,1);p.followers=Math.max(0,p.followers-1);me().following=Math.max(0,me().following-1)}save();R()},
chat(v){D.dm[v]=D.dm[v]||[];S.rep=S.edit=null;go({page:'chat',cu:v})},emo(v){const i=E('msg');i.value+=v;i.focus()},
send(){const i=E('msg'),t=i.value.trim();if(!t)return;const u=S.cu,ms=D.dm[u];if(S.edit){const m=ms.find(x=>x.id==S.edit);m.t=t;m.ed=1;S.edit=null}else{const m={id:D.id++,me:1,t,seen:0,rep:S.rep};ms.push(m);S.rep=null;setTimeout(()=>{m.seen=1;save();if(S.page=='chat'&&S.cu==u)R()},700);setTimeout(()=>{ms.push({id:D.id++,me:0,t:rnd(['हाँ भाई 😂','Pakka! 🔥','Haha sahi hai 😁','Okay done ✅','Kal milte hain ❤️']),seen:1});save();if(S.page=='chat'&&S.cu==u)R();else addNt(u,'ne aapko message bheja')},1600)}save();R();E('msg').focus()},
mrep(v){S.rep=+v;S.edit=null;R();E('msg').focus()},medit(v){S.edit=+v;S.rep=null;R();E('msg').focus()},mcancel(){S.rep=S.edit=null;R()},mdel(v){D.dm[S.cu]=D.dm[S.cu].filter(m=>m.id!=v);save();R()},
mkpost(){pick('image/*,video/*',(s,t)=>{S.tmp={src:s,type:t,r:0};postModal()})},mkreel(){pick('video/*',(s)=>{S.tmp={src:s,type:'vid',r:1};postModal()})},
doPost(){const t=S.tmp,p={id:D.id++,u:D.cur,type:t.type,r:t.r,src:t.src,cap:E('pc').value,likes:[],cm:[],ts:Date.now()};D.posts.push(p);save();toast(t.r?'Reel share hui 🎬':'Post share hui 📷');simulate(p);go({tab:t.r?'reels':'home',page:null})},
editp:v=>editModal(v),eav(){pick('image/*',s=>{S.tmp.avatar=s;toast('Photo select hui — Save dabayein')})},hladd(){pick('image/*',s=>{const t=prompt('Highlight title?','New')||'New';S.tmp.hl.push({t,src:s});E('e_h').innerHTML=hlList()})},hldel(v){S.tmp.hl.splice(+v,1);E('e_h').innerHTML=hlList()},
esave(){const o=S.tmp.u,n=E('e_u').value.trim().toLowerCase().replace(/^@/,'');if(!/^[a-z0-9._]{3,30}$/.test(n))return toast('Username galat');if(n!=o&&D.P[n])return toast('Username pehle se hai');const p=D.P[o];Object.assign(p,{name:E('e_n').value,bio:E('e_b').value,website:E('e_w').value.trim(),followers:Math.max(0,+E('e_f').value||0),following:Math.max(0,+E('e_g').value||0),nPosts:Math.max(0,+E('e_p').value||0),avatar:S.tmp.avatar,hl:S.tmp.hl});rename(o,n);save();closeM();R();toast('Profile update (sirf local)')},
hl(v){const[u,i]=v.split('|'),h=D.P[u].hl[+i];M(`<h3>${esc(h.t)}</h3><img src="${h.src}" style="width:100%;border-radius:16px">`)},
story(v){viewStory(v,0)},svn(v){const[u,i]=v.split('|');viewStory(u,+i+1)},
ed_open:()=>edOpen(),ed_x:edClose,
ed_gal:()=>pick('image/*,video/*',(s,t)=>{ed.base={t,src:s};bgSet()}),ed_mus:()=>pick('audio/*',s=>{ed.audio=s;const a=E('eda');a.src=s;a.play();toast('Music story me add hua 🎵')}),
ed_txt(){const t=prompt('Text likhein');if(!t)return;snap();ed.objs.push({k:'t',t,x:180,y:320,s:36,r:0,c:COL[ed.ci%COL.length],f:FNT[ed.fi%FNT.length]});ed.sel=ed.objs.length-1;drawEd()},
ed_stk:()=>pick('image/*',s=>{snap();ed.objs.push({k:'i',src:s,x:180,y:320,s:140,r:0});ed.sel=ed.objs.length-1;drawEd()}),
ed_drw(){ed.draw=!ed.draw;toast(ed.draw?'Draw ON ✏️ (color: ◐)':'Draw OFF')},ed_flt(){snap();ed.filter=(ed.filter+1)%FIL.length;bgSet();toast('Filter '+ed.filter+'/'+(FIL.length-1))},
ed_un(){if(!ed.un.length)return;ed.re.push(JSON.stringify({o:ed.objs,s:ed.strokes,f:ed.filter}));rest(ed.un.pop())},ed_re(){if(!ed.re.length)return;ed.un.push(JSON.stringify({o:ed.objs,s:ed.strokes,f:ed.filter}));rest(ed.re.pop())},
ed_del(){if(ed.sel>=0){snap();ed.objs.splice(ed.sel,1);ed.sel=-1}else if(ed.strokes.length){snap();ed.strokes.pop()}else if(ed.objs.length){snap();ed.objs.pop()}drawEd()},
ed_big(){const o=ed.objs[ed.sel];if(o){snap();o.s=Math.min(300,o.s*1.15);drawEd()}},ed_sml(){const o=ed.objs[ed.sel];if(o){snap();o.s=Math.max(14,o.s/1.15);drawEd()}},ed_rot(){const o=ed.objs[ed.sel];if(o){snap();o.r=(o.r+15)%360;drawEd()}},
ed_col(){ed.ci++;const o=ed.objs[ed.sel];if(o&&o.k=='t'){snap();o.c=COL[ed.ci%COL.length];drawEd()}else toast('Draw color badla')},ed_fnt(){ed.fi++;const o=ed.objs[ed.sel];if(o&&o.k=='t'){snap();o.f=FNT[ed.fi%FNT.length];drawEd()}},
ed_ok(){ed.sel=-1;drawEd();D.stories.unshift({id:D.id++,u:D.cur,base:ed.base,filter:ed.filter,ov:E('cv').toDataURL('image/png'),audio:ed.audio,ts:Date.now()});save();edClose();toast('Story share hui ✨');go({tab:'home',page:null})},
rtap(v,t,e){if(e.target.closest('.side'))return;const w=t.querySelector('video');if(w)w.paused?w.play():w.pause();else t.classList.toggle('paused')},mute(v,t,e){const w=t.closest('.reel').querySelector('video');if(w){w.muted=!w.muted;t.textContent=w.muted?'🔇':'🔊'}else toast('Is demo reel me audio nahi')},
pw(){const p=prompt('Naya password (min 4)');if(p&&p.length>=4){D.accts[D.cur]=H(p);save();toast('Password badla (local)')}},logout(){D.cur=null;S.mode='choose';S.page=null;save();R(1)},
export(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(D)],{type:'application/json'}));a.download='instalume-local-data.json';a.click()},
async reset(){if(!confirm('Poora local demo data delete hoga. Pakka?'))return;D=seed();await saveNow();S={mode:'choose',tab:'home',page:null};R(1);toast('Simulation reset ho gaya')}};
function postModal(){const t=S.tmp;M(`<h3>${t.r?'New Reel':'New Post'}</h3><div class="media" style="border-radius:16px">${media({type:t.type,src:t.src},0)}</div><textarea id="pc" placeholder="Caption likhein…"></textarea><button class="btn" data-a="doPost">Share</button>`)}
document.addEventListener('click',e=>{const t=e.target.closest('[data-a]');if(!t)return;const f=A[t.dataset.a];if(f){if(t.tagName=='A'&&t.hasAttribute('download'))return;f(t.dataset.v,t,e)}});
document.addEventListener('input',e=>{if(e.target.id=='q'){S.q=e.target.value;E('res').innerHTML=resV(S.q)}});
document.addEventListener('keydown',e=>{if(e.key!='Enter')return;const i=e.target.id;if(i=='msg')A.send();else if(i=='cmt')document.querySelector('[data-a=cpost]')?.click();else if(i=='ap'||i=='ap2')document.querySelector('.auth .btn')?.click()});
document.addEventListener('change',e=>{const c=e.target.dataset.c;if(!c)return;const v=e.target.type=='checkbox'?e.target.checked:e.target.value;if(c=='priv')me().private=v;else D.set[c]=v;save();theme();if(c=='lang')R()});
(async()=>{D=(await load())||seed();theme();R(1);setTimeout(()=>E('splash').classList.add('out'),1800);if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{})})();
